#pragma once

#include <cstdint>
#include <string>
#include <cstdio>
// #include "stm32f4xx_hal.h"
// https://community.st.com/stm32-mcus-embedded-software-32/some-files-in-the-hal-driver-and-cmsis-libraries-are-causing-errors-when-creating-a-c-project-154497
// https://community.st.com/stm32cubeide-mcus-28/solved-undefined-hal-statustypedef-when-compiling-hal-drivers-hundreds-of-times-32630
#include "can.h"
#include "stm32f4xx_hal_can.h"

#include "Utils.hpp"
#include "stm32f4xx_hal_def.h"


class CanBus {
    // The API for controlling CAN Bus communication is "documented" in the file
    // STM32_CubeMX_Generated_Code/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c
    //
    // I say "documented" (with quotes), because the comments there weren't quite enough to
    // fully understand how to use the API. In fact, even finding this documentation wasn't trivial!
    //
    // I started by going to the product page for the specific version of the STM32 we're using:
    // https://www.st.com/content/st_com/en/products/microcontrollers-microprocessors/stm32-32-bit-arm-cortex-mcus/stm32-high-performance-mcus/stm32f4-series/stm32f446/stm32f446re.html
    // I was greeted by over 50 different PDF's in the documentation section, so I turned to Gemini
    // for guidance on where to start. It turns out the main things you need to know to program the chip
    // aren't in the "User Manual", and also aren't in the "Programming Manual", but rather in the
    // "Reference Manual". Though in ST's defense, the "Programming Manual" does cover programming,
    // its just at the level of the literal ISA of the chip (a.k.a. assembly instructions)!
    //
    // The "Reference Manual" is a bit better, it describes things in terms of registers that
    // control each perhipheral, and which bits you need to set in each register to trigger
    // the diffrent functionalities. The problem was that even if I knew which bits to write
    // into which registers, I didn't see any documentation on how to get acces to a given register
    // in the code! I didn't see anything saying "This register is located at this address" or
    // anything like that. While writing this, I decided to go looking a little more, and after
    // some googling, found that the addresses of each register are documented at the end of the
    // section for the prehipheral your looking for (at least, that was the case for the CAN bus docs),
    // but those addresses are only given as offsets from some other main address, which you have to
    // scroll all the way to the top of the document to find (in the "register boundary addresses" section).
    // https://www.reddit.com/r/embedded/comments/1283n4e/where_are_stm32_register_addresses_documented/
    // https://www.reddit.com/r/embedded/comments/e92hgi/where_to_find_stm32_register_definitions_for_bare/
    // 
    // But even though I eventually found it, I would much prefer to be programming at the level
    // of using functions with meaninful names, rather than individual bit twiddling.
    // I figured that this must be something that they provide, and it turns out this is what the
    // HAL is (HAL stands for Hardware Abstraction Layer, idk why they don't just call it the libraries).
    //
    // It turns out that the docs for the HAL aren't even included on the product page for the chip though! 
    // I learned this from googling "stm32 hal library docs" and eventually arriving at this thread:
    // https://www.reddit.com/r/stm32f4/comments/95406y/documentation_on_hal_libraries_functions/
    //
    // While this is better, I still didn't immediately see any way to import these libraries
    // or how to find them. So I turned to google once again and eventually found out that the
    // libraries are automatically included in the project for you when you generate a project
    // using one of ST's code generation tools. They have two apps that they offer:
    //
    // 1) STM32 CubeMX: This is a GUI that lets you configure certain aspects of the chip
    //    via drop down menus and whatnot, and then it generates the equivalent code for you.
    //
    // 2) STM32 CubeIDE: This is a full fledged dev environment that does the code genration,
    //    and also serves as an editor. However, we prefer to just use VSCode, so we just
    //    use the CubeMX tool to generate the starter code, and then edit it in VSCode.
    //
    // Simon made me aware of some quirks with the autogenerated code, namely that if you insert
    // any of your own code inside the auto-generated files, then it risks getting overwritten
    // each time you change your configuration and need to generate new starter code from the GUI,
    // unless you put your code in specially marked "User code blocks" (delimited by comments)
    // that the code generator won't touch when generating new code.
    //
    // That sounds like hell to deal with, and I'd much rather organize my code the way I like
    // rather than be forced into putting in the places where their tool "permits" me to.
    // Additionally, I'd like to program in c++ for the extra encapsulation it offers,
    // but the code generated by the tool is always in pure C. Some more googling
    // indicated that the best option was to just leave the auto-generated code alone,
    // write all your code seperately, and then call into your main function from their code,
    // so that's what we're gonna do. That's why the project is seperated into two folders at the top
    // level:
    // 1) "STM32_CubeMX_Generated_Code/"
    // 2) "Code_Written_By_Humans/"
    // 
    // Had to read a few of these regarding geting c++ support too:
    // https://community.st.com/stm32cubemx-mcus-29/c-support-in-cubemx-150193
    // https://kleinembedded.com/cpp-and-stm32cubemx-code-generation/
    // https://isocpp.org/wiki/faq/mixing-c-and-cpp
    // https://zenembed.com/vscode-cubemx-guide
    // https://heyeduardo.com/posts/modern-c++-development-on-stm32/ <-- This one actually gets you most of the way there. I just wish he called out the #include for the HAL in c++, and talked about extern "C" some more because you will need it for the callbacks. But other than that, this has everything! 
    // https://www.st.com/content/st_com/en/campaigns/stm32-vs-code-extension-z11.html
    // https://dev.st.com/stm32cube-docs/stm32cubeide-vscode/1.0.1/en/index.html
    // https://dev.st.com/stm32cube-docs/stm32cubeide-vscode/1.0.1/en/docs/markup/basic_concepts/cmake.html
    // 
    //
    //
    // But anyway, back to the HAL and the interfaces it provides. While googling, I learned
    // that the the docs for the peripherals you configured in the CubeMX tool are actually,
    // included in the autogenerated source code!
    // I eventually found them in:
    // STM32_CubeMX_Generated_Code/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c
    //
    // Note that some of the docs / definitions you need for using the registers directly
    // are supposedly  included in the /Drivers/ folder, just under the /CMSIS/ folder
    // instead of the /STM32F4xx_HAL_Driver/ folder. We're still gonna use the higher level
    // library, just thought I'd mention it.

    // Anyway, with all of that out of the way, now we can talk about the can API that's
    // documented in STM32_CubeMX_Generated_Code/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c
    // Note that the documentation was a little unclear in placces, so I got Gemini to help clarify a few things.
    // I did my own followup research by googling and cross checking the source code, and synthesized my
    // findings in the comment below:
    //
    //
    //
    // It looks like the STM32 libraries provide 3 different APIs for
    // interacting with and controlling the hardware:
    // 1) A polling-based API
    // 2) An interrupt based API, where callbacks are registered via function pointers
    // 3) A different interrupt based API, where the callback functions are already
    //    defined, but have blank implementations that you need to fill in.
    //
    //    One weird quirk about this last option, is that you actually don't have to go
    //    to the file where they defined the function and fill in the braces there.
    //    Apparently, all you need to do is to define a function with the exact same
    //    name and signature anywhere in your codebase, and the compiler/linker will
    //    pick up on that automatically and use your implementation.
    //
    //    This is done via a weird feature in C that I had never heard of before
    //    called "weak" functions. It seems pretty similar to the idea of "overriding" methods
    //    that are inherited from a parent class in c++, except there isn't a parent class,
    //    you're just overriding a single function everywhere its used. If you never provide
    //    an override, then the function will just use its default implementation
    //    (which is whatever you put into the curly brackets at the side where the function was
    //     declared with the "weak" keyword).
    //
    //    Sources: https://electronics.stackexchange.com/questions/602470/what-is-the-meaning-of-the-keyword-weak-in-this-callback-function-in-hal-gpi
    //             https://stackoverflow.com/questions/72176417/which-c-standard-introduced-the-weak-keyword
    //
    //
    // From looking at Simon's existing code, it seems he went with option 3,
    // so that's what I'll do here too.

    private:
        uint32_t myCanId = 1;
    
    public:
        // public shit goes here, including constructors?
        CanBus() {
            // CubeMX already genrates some of the starter code needed to get CAN up and running.
            // Here's a quick summary of the autogenerated code (read "->" as "calls")
            //
            // main.c  ->  MX_CAN1_Init()  ->  HAL_CAN_Init()  ->  HAL_CAN_MspInit()
            //                   |                   |                     |
            // defined in:     can.c         stm32f4xx_hal_can.c    weakly declared in
            //                                                      stm32f4xx_hal_can.c,
            //                                                      but the real auto-generated
            //                                                      definition is in can.c
            //
            // The leftover stuff for us to do here
            // (as per the docs in stm32f4xx_hal_can.c)
            // is to:
            // 1) Configure Filters (whatever that means) via HAL_CAN_ConfigFilter();
            // 2) Allow interrupts (if we're using that part of the api) via HAL_CAN_ActivateNotification();
            // 3) Actually start up the CAN module on the chip via HAL_CAN_Start();
            //
            // And that's it (as far as I can tell)!

            // HAL_CAN_ConfigFilter() requries a pointer to an object of type
            // "CAN_HandleTypeDef". It looks like that object has already been created for us
            // (and used for some of the auto-generated setup code) in "can.c".
            // Now I need to figure out if we can access that through the "stm32f4xx_hal.h" import
            // that we do at the top, or if there's some other way we need to get to it.
            // 
            // Now read "->" as "imports"
            //
            // "stm32f4xx_hal.h"  ->  "stm32f4xx_hal_conf.h"  ->  "stm32f4xx_hal_can.h"  ->  we never get it
            // It looks like I can get acces to it via "can.h" though. Let's see if that breaks anything...
            // Update: Looks good so far, I've changed the import!
            CAN_HandleTypeDef* pointerToCanStuff = &hcan1; // <- lives in "can.c", provided to us by "can.h"
            
            // Actual filter params we can just pass in ourselves.
            // The options are defined in "stm32f4xx_hal_can.h";
            // The actual meaning of these options is defined in the
            // reference manual (RM0390), (command-F for "Identifier filtering", it's section 30.7.4)
            // https://youtu.be/bmtOyr7UYNo?si=CpSMmZKwkkPWHWCI <- this was also helpful for reading the diagarm they have
            //
            // We don't have tons of devices on the bus, so we'll be using 11 bit identifiers
            // (I doubt anyone using the 29 bit identifier actually has 2^29 devices on one bus!)
            // 
            // These filter settings correspond to a series of tests that the hardware
            // will perform on all incomming CAN messages before forwarding them to the software.
            // Messages that don't get past the filter are just discarded, and not seen by the software.
            // Because messages on a CAN bus are sent to EVERY device on the bus, the main purpose
            // of the filter is to make it so you only have to worry about messages that are addressed to you
            // and you don't have to waste any precious CPU cycles actively rejecting messages that weren't
            // meant for you anyway.
            //
            // By default, each "test" consists of a [bit pattern] and a [mask].
            // The [mask] is used to select which bits in the [bit pattern] 
            // must be matched by incomming CAN messages (specifically, their 11 bit ID field),
            // in order to be accepted and forwarded to the software.
            //
            // Here are a couple examples (using 8 bit IDs, just for the sake of space):
            //
            // "Only accept CAN messages addressed to ID 5":
            // [bit pattern] = 0 0 0 0 0 1 0 1  (this is the bit pattern for "5" as an unsigned 8-bit integer)
            // [mask] =        1 1 1 1 1 1 1 1  (i.e. every single bit must match in order for the message to be accepted)
            //
            // "Only accept CAN messages that are addressed to [ANY ID THAT IS 15 OR LESS]"
            //  [bit pattern] = 0 0 0 0 X X X X  (every unsigned 8-bit integer that's less than or equal to 15 starts with four zeros)
            //  [mask]        = 1 1 1 1 0 0 0 0  (It doesn't matter what we put for the X's, because the mask has 0's in those locations.
            //                                    The incomming message only needs to match our [bit pattern] in the places where the [mask]
            //                                    is set to '1'. I put an 'X' in the [bit pattern] everywhere the [mask] had a '0' to indicate
            //                                    that we could've used either a '0' or a '1' at that location in the [bit pattern], and it wouldnt've
            //                                    made a difference because of the [mask].)
            //
            //
            // https://electronics.stackexchange.com/questions/506180/can-bus-dominant-and-recessive
            // https://en.wikipedia.org/wiki/CAN_bus
            // https://youtu.be/bmtOyr7UYNo?si=CpSMmZKwkkPWHWCI <- this was also helpful for reading the diagarm they have
            // 
            // In reality, the [bit pattern] and [mask] registers for a given test are each 32 bits
            // (because CAN can work with up to 29 bit IDs. Here is how we're supposed fit our data
            // into those 32 bit registers (This comes from Figure 391 (section 30.7.4) in the datasheet):
            // (Most significant bits on the left, least significant bits on the right):
            //
            //                         followed by 18 additional
            //                         bits for if you're using
            //                         extended IDs             'R' = A single bit indicating  
            //                                   |              if the given frame is a "data frame" (R=0)
            //                                   |              or a "remote/request frame" (R=1)
            //                                   |              (check the wikipedia page for info)
            //                     11            |          29   |
            //       [SSSS SSSS SSS][E EEEE EEEE EEEE EEEE E][B][R][0] <- The final bit to fill out the 32 bit register is always 0.
            //               |                                |
            //     11 bit standard id                 'B' = A single bit
            //                                        indicating if this is
            //                                        and 11 bit ID (D=0) or
            //                                        a 29 bit extended ID (D=1)     
            // 
            CAN_FilterTypeDef filterSettings;

            filterSettings.FilterMode = CAN_FILTERMODE_IDMASK;
            filterSettings.FilterScale = CAN_FILTERSCALE_32BIT;

            filterSettings.FilterBank = 0; // TODO: loop over all banks and explicitly disable unused banks, or check if that's already done in the datasheet.
            filterSettings.FilterActivation = CAN_FILTER_ENABLE;
            filterSettings.FilterFIFOAssignment = CAN_FILTER_FIFO0; // TODO: check this
            filterSettings.SlaveStartFilterBank = 0; // unused

            // TODO: actually put the bits in the correct place per the diagram above,
            //       and also account for the extra 2 bits at the end and make sure the final bit is 0...
            filterSettings.FilterIdLow = myCanId & Utils::getBitMask(0, 16);
            filterSettings.FilterIdHigh = (myCanId & Utils::getBitMask(16, 32)) >> 16;

            filterSettings.FilterMaskIdLow = Utils::getBitMask(0, 16);
            filterSettings.FilterMaskIdHigh = Utils::getBitMask(0, 16);

            // lol
            // https://community.st.com/stm32-mcus-products-25/time-triggered-can-communication-support-70636
            // 
            HAL_StatusTypeDef errorCodeFromFilterConfig = HAL_CAN_ConfigFilter(pointerToCanStuff, &filterSettings);
            if (errorCodeFromFilterConfig != HAL_OK) {
                // TODO: some error response.
                //       Maybe just auto retry or something...
                return;
            }
        }

        void sayHello() {
            // std::string myAmazingString = "Hello, World!";
            // std::printf(myAmazingString.c_str());
            // https://www.reddit.com/r/embedded/comments/1bby3qt/the_definitive_guide_to_enabling_printf_on_an/
            // https://stackoverflow.com/questions/25789644/what-is-the-difference-between-using-a-makefile-and-cmake-to-compile-the-code
            // 
        }
};