#pragma once

class CanBus {
    // The API for controlling CAN Bus communication is "documented" in the file
    // STM32_CubeMX_Generated_Code/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c
    //
    // I say "documented" (with quotes), because the comments there weren't quite enough to
    // fully understand how to use the API. In fact, even finding this documentation wasn't trivial!
    //
    // I started by going to the product page for the specific version of the STM32 we're using:
    // https://www.st.com/content/st_com/en/products/microcontrollers-microprocessors/stm32-32-bit-arm-cortex-mcus/stm32-high-performance-mcus/stm32f4-series/stm32f446/stm32f446re.html
    // I was greeted by over 50 different PDF's in the documentation section, so I turned to Gemini
    // for guidance on where to start. It turns out the main things you need to know to program the chip
    // aren't in the "User Manual", and also aren't in the "Programming Manual", but rather in the
    // "Reference Manual". Though in ST's defense, the "Programming Manual" does cover programming,
    // its just at the level of the literal ISA of the chip (a.k.a. assembly instructions)!
    //
    // The "Reference Manual" is a bit better, it describes things in terms of registers that
    // control each perhipheral, and which bits you need to set in each register to trigger
    // the diffrent functionalities. The problem was that even if I knew which bits to write
    // into which registers, I didn't see any documentation on how to get acces to a given register
    // in the code! I didn't see anything saying "This register is located at this address" or
    // anything like that. While writing this, I decided to go looking a little more, and after
    // some googling, found that the addresses of each register are documented at the end of the
    // section for the prehipheral your looking for (at least, that was the case for the CAN bus docs),
    // but those addresses are only given as offsets from some other main address, which you have to
    // scroll all the way to the top of the document to find (in the "register boundary addresses" section).
    // https://www.reddit.com/r/embedded/comments/1283n4e/where_are_stm32_register_addresses_documented/
    // https://www.reddit.com/r/embedded/comments/e92hgi/where_to_find_stm32_register_definitions_for_bare/
    // 
    // But even though I eventually found it, I would much prefer to be programming at the level
    // of using functions with meaninful names, rather than individual bit twiddling.
    // I figured that this must be something that they provide, and it turns out this is what the
    // HAL is (HAL stands for Hardware Abstraction Layer, idk why they don't just call it the libraries).
    //
    // It turns out that the docs for the HAL aren't even included on the product page for the chip though! 
    // I learned this from googling "stm32 hal library docs" and eventually arriving at this thread:
    // https://www.reddit.com/r/stm32f4/comments/95406y/documentation_on_hal_libraries_functions/
    //
    // While this is better, I still didn't immediately see any way to import these libraries
    // or how to find them. So I turned to google once again and eventually found out that the
    // libraries are automatically included in the project for you when you generate a project
    // using one of ST's code generation tools. They have two apps that they offer:
    //
    // 1) STM32 CubeMX: This is a GUI that lets you configure certain aspects of the chip
    //    via drop down menus and whatnot, and then it generates the equivalent code for you.
    //
    // 2) STM32 CubeIDE: This is a full fledged dev environment that does the code genration,
    //    and also serves as an editor. However, we prefer to just use VSCode, so we just
    //    use the CubeMX tool to generate the starter code, and then edit it in VSCode.
    //
    // Simon made me aware of some quirks with the autogenerated code, namely that if you insert
    // any of your own code inside the auto-generated files, then it risks getting overwritten
    // each time you change your configuration and need to generate new starter code from the GUI,
    // unless you put your code in specially marked "User code blocks" (delimited by comments)
    // that the code generator won't touch when generating new code.
    //
    // That sounds like hell to deal with, and I'd much rather organize my code the way I like
    // rather than be forced into putting in the places where their tool "permits" me to.
    // Additionally, I'd like to program in c++ for the extra encapsulation it offers,
    // but the code generated by the tool is always in pure C. Some more googling
    // indicated that the best option was to just leave the auto-generated code alone,
    // write all your code seperately, and then call into your main function from their code,
    // so that's what we're gonna do. That's why the project is seperated into two folders at the top
    // level:
    // 1) "STM32_CubeMX_Generated_Code/"
    // 2) "Code_Written_By_Humans/"
    // 
    // Had to read a few of these regarding geting c++ support too:
    // https://community.st.com/stm32cubemx-mcus-29/c-support-in-cubemx-150193
    // https://kleinembedded.com/cpp-and-stm32cubemx-code-generation/
    // https://isocpp.org/wiki/faq/mixing-c-and-cpp
    // https://zenembed.com/vscode-cubemx-guide
    // https://heyeduardo.com/posts/modern-c++-development-on-stm32/
    // https://www.st.com/content/st_com/en/campaigns/stm32-vs-code-extension-z11.html
    //
    //
    // But anyway, back to the HAL and the interfaces it provides. While googling, I learned
    // that the the docs for the peripherals you configured in the CubeMX tool are actually,
    // included in the autogenerated source code!
    // I eventually found them in:
    // STM32_CubeMX_Generated_Code/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c
    //
    // Note that some of the docs / definitions you need for using the registers directly
    // are supposedly  included in the /Drivers/ folder, just under the /CMSIS/ folder
    // instead of the /STM32F4xx_HAL_Driver/ folder. We're still gonna use the higher level
    // library, just thought I'd mention it.

    // Anyway, with all of that out of the way, now we can talk about the can API that's
    // documented in STM32_CubeMX_Generated_Code/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c
    // Note that the documentation was a little unclear in placces, so I got Gemini to help clarify a few things.
    // I did my own followup research by googling and cross checking the source code, and synthesized my
    // findings in the comment below:
    //
    //
    //
    // It looks like the STM32 libraries provide 3 different APIs for
    // interacting with and controlling the hardware:
    // 1) A polling-based API
    // 2) An interrupt based API, where callbacks are registered via function pointers
    // 3) A different interrupt based API, where the callback functions are already
    //    defined, but have blank implementations that you need to fill in.
    //
    //    One weird quirk about this last option, is that you actually don't have to go
    //    to the file where they defined the function and fill in the braces there.
    //    Apparently, all you need to do is to define a function with the exact same
    //    name and signature anywhere in your codebase, and the compiler/linker will
    //    pick up on that automatically and use your implementation.
    //
    //    This is done via a weird feature in C that I had never heard of before
    //    called "weak" functions. It seems pretty similar to the idea of "overriding" methods
    //    that are inherited from a parent class in c++, except there isn't a parent class,
    //    you're just overriding a single function everywhere its used. If you never provide
    //    an override, then the function will just use its default implementation
    //    (which is whatever you put into the curly brackets at the side where the function was
    //     declared with the "weak" keyword).
    //
    //    Sources: https://electronics.stackexchange.com/questions/602470/what-is-the-meaning-of-the-keyword-weak-in-this-callback-function-in-hal-gpi
    //             https://stackoverflow.com/questions/72176417/which-c-standard-introduced-the-weak-keyword
    //
    //
    // From looking at Simon's existing code, it seems he went with option 3,
    // so that's what I'll do here too.

    private:
        // private variables go here
    
    public:
        // public shit goes here, including constructors?
        CanBus() {
            // Need to do these?
            // 1) HAL_CAN_ConfigFilter()?
            // 2) HAL_CAN_Start(); //  can now recieve and send messages


        }
};